name: Matrix

on:
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        images: ["hello-world", "alpine"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run echo
        run: echo ${{ matrix.images }}

# With matrix you can run a job for each combination of the matrix values. This is useful to avoid repetition. 
# In this case, it will execute 2x2=4 times (2 possible values for os and 2 possible values for images).
