name: Manual Trigger

on:
# You can add multiple options to set values when the workflow runs. These will shop up in the UI
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Run tests?"
        type: boolean
        required: true
      test-type:
        description: "Type of test to run"
        type: choice
        options:
          - unit
          - integration
          - all
      environment:
        description: "Choose an environment"
        required: true
        type: environment
      build-number:
        type: number
      message:
        type: string

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    
      - name: Docker Login
          # Sensitive information like passwords can be stored inside github's secrets Settings > Variables and Secrets > Actions
        run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
