name: My First Workflow

on: [push, fork]

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: List and Read File
        run: |
          echo "My first GitHub Actions Job"
          ls
          cat README.md

      # Will fail, this third-party library is not present on the vm
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      
      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md
